services:
  postgres-auth:
    image: postgres:16
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: auth_pass
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U auth_user -d auth_db"]
      interval: 5s
      timeout: 5s
      retries: 10

  auth-service:
    build:
      context: ./auth-service
    depends_on:
      postgres-auth:
        condition: service_healthy
    environment:
      PORT: "8001"
      MASTER_KEY: "change-me-master-key"
      DATABASE_URL: "postgresql://auth_user:auth_pass@postgres-auth:5432/auth_db"
    ports:
      - "8001:8001"

  postgres-flags:
    image: postgres:16
    environment:
      POSTGRES_DB: flags_db
      POSTGRES_USER: flags_user
      POSTGRES_PASSWORD: flags_pass
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U flags_user -d flags_db"]
      interval: 5s
      timeout: 5s
      retries: 10

  flag-service:
    build:
      context: ./flag-service
    depends_on:
      postgres-flags:
        condition: service_healthy
      auth-service:
        condition: service_started
    environment:
      PORT: "8002"
      DATABASE_URL: "postgresql://flags_user:flags_pass@postgres-flags:5432/flags_db"
      AUTH_SERVICE_URL: "http://auth-service:8001"
    ports:
      - "8002:8002"

  targeting-service:
    build:
      context: ./targeting-service
    depends_on:
      postgres-flags:
        condition: service_healthy
      auth-service:
        condition: service_started
      flag-service:
        condition: service_started
    environment:
      PORT: "8003"
      DATABASE_URL: "postgresql://flags_user:flags_pass@postgres-flags:5432/flags_db"
      AUTH_SERVICE_URL: "http://auth-service:8001"
      FLAG_SERVICE_URL: "http://flag-service:8002"
    ports:
      - "8003:8003"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  evaluation-service:
    build:
      context: ./evaluation-service
    depends_on:
      redis:
        condition: service_started
      flag-service:
        condition: service_started
      targeting-service:
        condition: service_started
    environment:
      PORT: "8004"
      REDIS_URL: "redis://redis:6379"
      FLAG_SERVICE_URL: "http://flag-service:8002"
      TARGETING_SERVICE_URL: "http://targeting-service:8003"
      SERVICE_API_KEY: "local-dev-key"
      AWS_REGION: "us-east-1"
      AWS_SQS_URL: ""
    ports:
      - "8004:8004"

  dynamodb:
    image: amazon/dynamodb-local
    command: ["-jar", "DynamoDBLocal.jar", "-inMemory", "-sharedDb"]
    ports:
      - "8000:8000"

  analytics-service:
    build:
      context: ./analytics-service
    depends_on:
      dynamodb:
        condition: service_started
    environment:
      PORT: "8005"
      AWS_REGION: "us-east-1"
      AWS_DYNAMODB_TABLE: "analytics"
      AWS_SQS_URL: ""
      # endpoint do DynamoDB local (container -> container)
      DYNAMODB_ENDPOINT_URL: "http://dynamodb:8000"
    ports:
      - "8005:8005"
