# syntax=docker/dockerfile:1
FROM golang:1.22-alpine AS build
WORKDIR /src
RUN apk add --no-cache git
COPY go.mod ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o app .

FROM gcr.io/distroless/static:nonroot
WORKDIR /
COPY --from=build /src/app /app
USER nonroot:nonroot
EXPOSE 8001
ENTRYPOINT ["/app"]