name: auth CI

on:
  push:
    paths:
      - "auth-service/**"
      - ".github/workflows/auth-ci.yml"

jobs:
  build-test-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Debug estrutura
        run: |
          pwd
          ls -la
          ls -la auth-service
          cat auth-service/go.mod

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"
          cache: false

      - name: Download deps
        run: cd auth-service && go mod download

      - name: Test
        run: cd auth-service && go test ./...

      - name: Build binary
        run: cd auth-service && go build -o app main.go

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build image
        run: cd auth-service && docker build -t auth-service:latest .

      - name: Tag image
        run: docker tag auth-service:latest 975050093343.dkr.ecr.us-east-1.amazonaws.com/auth-service:latest

      - name: Push image
        run: docker push 975050093343.dkr.ecr.us-east-1.amazonaws.com/auth-service:latest