name: auth CI

on:
  push:
    paths:
      - "auth-service/**"
  pull_request:
    paths:
      - "auth-service/**"

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: auth-service

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22

      - name: Download deps
        run: go mod download

      - name: Test
        run: go test ./...

      - name: Build binary
        run: go build -o app main.go

      - name: Build Docker image
        run: docker build -t auth-service .

      - name: Security scan
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: auth-service